# fly.toml app configuration file generated for twitchbot-njnncw on 2026-01-01T15:13:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'twitchbot-njnncw'
primary_region = 'fra'

[env]
  MIN_MACHINES_RUNNING = "1"

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory = '4gb'
  memory_mb = 4096
